### ISSUE TITLE
How is the data format organized when training llama?

### ISSUE THREAD

**Issue by LeiyanGithub** [choosewhatulike/trainable-agents#1]
这种数据格式和vicuna类似的组织格式不一样呢，在执行的时候会报错
<img width="671" alt="image" src="https://github.com/choosewhatulike/trainable-agents/assets/45895439/c3ef7c1e-482b-46cb-ad86-e051f8fd9111">

所以想请教一下，训练最终是不是应该组织成这种多轮的格式呢？
<img width="639" alt="image" src="https://github.com/choosewhatulike/trainable-agents/assets/45895439/aae27f12-5da3-4485-bc1a-ad2a19607c79">

**Comment by choosewhatulike** [comment]
请用prompted/目录下的数据，已经format好了
