### ISSUE TITLE
question about  protective scenes in training dataset.

### ISSUE THREAD

**Issue by pull-ups** [choosewhatulike/trainable-agents#2]
I downloaded train dataset from huggingface fnlp. Among the samples of dataset of each character, Are "protective scene" samples included in them? How can I discriminate those samples?

 I feel really impressive of your work and I'm following your process.Thanks.

**Comment by choosewhatulike** [comment]
Thanks for your attention.
Yeah, the "protective scenes" are included in training data, you can pick them up in the `generated` folder, with `hallucination` in the file name.
