### ISSUE TITLE
Script incorrection in READ.ME

### ISSUE THREAD

**Issue by 17000cyh** [choosewhatulike/trainable-agents#4]
hi, thanks for your impressive work !

however, it seems like that a line of you script has sth wrong:

python parser/parse_data_hallucination.py result/2023-10-08/gen_dialogue/gpt-3.5-turbo-temp-0.2-char-Beethoven.jsonl

should be

python parser/parse_data_dialogue.py result/2023-10-08/gen_dialogue/gpt-3.5-turbo-temp-0.2-char-Beethoven.jsonl 

in the third step while dealing with data ?

**Comment by choosewhatulike** [comment]
Yes, there is a typo. I have updated the new script. Thank you for pointing it out.
