### ISSUE TITLE
How to generate more dataset?

### ISSUE THREAD

**Issue by PuTaTus** [choosewhatulike/trainable-agents#6]
Hi there, each prompt only give me 20 ish prompts. How can I generate as much dataset as shown in the github docs?

**Comment by choosewhatulike** [comment]
You can follow instructions step by step in our README at [Dataset](https://github.com/choosewhatulike/trainable-agents?tab=readme-ov-file#dataset)

**Comment by PuTaTus** [comment]
Thank you! The issue is solved.
