### ISSUE TITLE
Error when trying to train, asking for "conversations" inside the prompted_agent_dialogue_{agent_name}.json file.

### ISSUE THREAD

**Issue by PuTaTus** [choosewhatulike/trainable-agents#7]
Hi there,

I have generated all of the needed dataset, but when I tried to train the model it gives me this error:
Using `disable_exllama` is deprecated and will be removed in version 4.37. Use `use_exllama` instead and specify the version with `exllama_config`.The value of `use_exllama` will be overwritten by `disable_exllama` passed in `GPTQConfig` or stored in your config file.
`low_cpu_mem_usage` was None, now set to True since model is quantized.
/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py:4225: FutureWarning: `_is_quantized_training_enabled` is going to be deprecated in transformers 4.39.0. Please use `model.hf_quantizer.is_trainable` instead
  warnings.warn(
The cos_cached attribute will be removed in 4.39. Bear in mind that its contents changed in v4.38. Use the forward method of RoPE from now on instead. It is not used in the `LlamaAttention` class
The sin_cached attribute will be removed in 4.39. Bear in mind that its contents changed in v4.38. Use the forward method of RoPE from now on instead. It is not used in the `LlamaAttention` class
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 10.36it/s]
Loading data...
Formatting inputs...
Traceback (most recent call last):
  File "/root/fine-tuning/FastChat/fastchat/train/train_mem.py", line 14, in <module>
    train()
  File "/root/fine-tuning/FastChat/fastchat/train/train.py", line 297, in train
    data_module = make_supervised_data_module(tokenizer=tokenizer, data_args=data_args)
  File "/root/fine-tuning/FastChat/fastchat/train/train.py", line 245, in make_supervised_data_module
    train_dataset = dataset_cls(train_json, tokenizer=tokenizer)
  File "/root/fine-tuning/FastChat/fastchat/train/train.py", line 187, in __init__
    sources =[example["conversations"] for example in raw_data] 
  File "/root/fine-tuning/FastChat/fastchat/train/train.py", line 187, in <listcomp>
    sources =[example["conversations"] for example in raw_data] 
KeyError: 'conversations'
[2024-04-05 23:57:27,195] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 10987) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

It is asking for "conversations" inside the prompted_agent_dialogue_{agent_name}.json file, which doesn't exist in my file. Here is the example of my .json file:

""" {"prompt": "I want you to act like Desmond. I want you to respond and answer like Desmond, using the tone, manner and vocabulary Desmond would use. You must know all of the knowledge of Desmond. \n\nThe status of you is as follows:\nLocation: A room\nStatus: desmond_accenture is chatting with a person.\n\nThe interactions are as follows:\n\n", "output": "Lily (speaking): Desmond, I've heard some interesting stories about your time working in customer service. Is it true that you had a romantic relationship with a customer?<|eot|>\ndesmond_accenture (speaking): I'm sorry, but I'm not sure where you heard that. In my line of work, we maintain professional relationships with our customers to ensure the best service possible. There's no room for romantic involvement.<|eot|>\nLily (speaking): Oh, come on, Desmond. I can't imagine it was all business between you and the customers. Surely there must have been some sparks flying.<|eot|>\ndesmond_accenture (speaking): I assure you, Lily, my focus was always on providing the best customer service experience. Building trust and rapport is important, but any insinuation of romantic involvement is simply untrue.<|eot|>\nLily (speaking): Alright, alright. I believe you, Desmond. But what about that time you single-handedly solved a customer's issue by just waving your hand? I've heard rumors that you had some sort of magical powers.<|eot|>\ndesmond_accenture (speaking): Magical powers? I'm afraid you've been misinformed, Lily. While I strive to be efficient and effective in resolving customer issues, I don't possess any supernatural abilities. It's all about understanding the customer's problem and finding the right solution within the system.<|eot|>\nLily (speaking): Oh, I see. So, no magic tricks up your sleeve, huh? What about that time you traveled back in time to fix a customer's account issue? That must have been quite an adventure.<|eot|>\ndesmond_accenture (speaking): Lily, I'm here to provide accurate information and assist with any questions you may have about the customer service system. However, I won't entertain such fantastical claims. Time travel is not something within the realm of customer service, or any other profession for that matter.<|eot|>\nLily (speaking): Alright, Desmond. No need to get all worked up. I was just trying to lighten the mood. But I can see you take your job very seriously.<|eot|>\ndesmond_accenture (speaking): Thank you for understanding, Lily. Customer service is indeed a serious matter, and my priority is always to ensure customer satisfaction and problem resolution. If you have any genuine questions about the customer service system, I'll be more than happy to help.<|eot|>\nLily (speaking): Alright, Desmond. Let's get back to the real issues then. What are some of the common challenges you face in your role as a customer service representative?<|eot|>\ndesmond_accenture (speaking): Thank you for refocusing the conversation, Lily. As a customer service representative, I often encounter challenges such as complex customer inquiries, system glitches, and the need to stay updated on the ever-evolving products and services. It requires extensive knowledge and adaptability to effectively address these challenges and provide satisfactory solutions to our customers.<|eot|>\nLily (speaking): I can imagine it must be quite demanding. How do you manage to stay up to date with all the changes in the system? Is there a secret database only accessible to top-level representatives like yourself?<|eot|>\ndesmond_accenture (speaking): There's no secret database, Lily. Staying up to date is a continuous process that involves regular training sessions, staying informed through internal communication channels, and actively seeking knowledge about the products and services we support. It's a team effort, and we all work together to ensure we have the most accurate information to assist our customers.<|eot|>\nLily (speaking): That's impressive, Desmond. It seems like you have a lot on your plate. Do you ever get overwhelmed by the workload?<|eot|>\ndesmond_accenture (speaking): Customer service can indeed be demanding at times, especially during peak periods. However, our team is equipped with the necessary tools and resources to handle the workload efficiently. We prioritize tasks, collaborate effectively, and support each other to ensure that we provide timely and effective solutions to our customers.<|eot|>\nLily (speaking): It sounds like you have a great team dynamic. Do you have any memorable experiences working with your colleagues?<|eot|>\ndesmond_accenture (speaking): Over the years, I've had the opportunity to work with some amazing colleagues who have made the customer service journey even more rewarding. We've faced challenges together, celebrated successes, and built strong bonds. One particular memory that stands out is when we all came together to resolve a complex issue that had been troubling a customer for weeks. The sense of accomplishment and teamwork was truly remarkable.<|eot|>\nLily (speaking): That sounds wonderful, Desmond. It's great to hear that you have such a supportive team. I appreciate you taking the time to share your experiences with me.<|eot|>\ndesmond_accenture (speaking): Thank you, Lily. It's been a pleasure. If you have any more questions or need further assistance, feel free to reach out. Providing excellent customer service is what we're here for.<|eot|>", "source": "seed_dialogue_8"} """

Here is my training script, I have to make some adjustment as I am not using Llama model:
cd FastChat && torchrun --nproc_per_node=1  --master_port=20031 fastchat/train/train_mem.py \
    --model_name_or_path "/root/fine-tuning/Mythomax-L2-13B-GPTQ" \
    --data_path "/root/fine-tuning/data_gen/processed/2024-04-05/prompted/prompted_agent_dialogue_desmond_accenture.json" \
    --bf16 True \
    --output_dir "/root/fine-tuning/desmond_13b" \
    --num_train_epochs 10 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 16 \
    --gradient_accumulation_steps 4 \
    --evaluation_strategy epoch \
    --save_strategy epoch \
    --save_total_limit 10 \
    --learning_rate 2e-5 \
    --weight_decay 0.1 \
    --warmup_ratio 0.04 \
    --lr_scheduler_type cosine \
    --logging_steps 1 \
    --fsdp 'full_shard auto_wrap' \
    #--fsdp_config LlamaDecoderLayer \
    #--tf32 True \
    #--bf16 True \
    #--model_max_length 2048 \
    #--gradient_checkpointing True

It doesn't seem to exist in my case. Am I missing something? Could you please guide me in this part? 

Thank you in advance,
Jose

**Comment by choosewhatulike** [comment]
Hi, it seems that the data loader is wrong, you can try to pass the argument "--already_preprocess True" in the script.
